
enum ScreenPaths{
authLoginScreenPath,
authVerifyScreenPath,
profileCompletionScreenPath,
homeDashBoardPath,
foodTrackScreenPath,
foodInsightsScreenPath,
foodSearchScreenPath,
workoutSearchScreenPath,
foodDetailScreenPath,
workoutTrackScreenPath,
workoutDetailScreenPath,
editProfileScreenPath
}